import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { openDB } from 'idb';

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache API requests for stories
registerRoute(
  ({ url }) => url.origin === 'https://story-api.dicoding.dev' && url.pathname.startsWith('/v1/stories'),
  new NetworkFirst({
    cacheName: 'stories-api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24, // 1 day
      }),
    ],
  })
);

// Cache other assets (images from API, etc.)
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Background Sync for Offline Story Creation
async function syncStories() {
  try {
    const db = await openDB('story-app-db', 1);
    const pendingStories = await db.getAll('pending-stories');

    for (const story of pendingStories) {
      try {
        const formData = new FormData();
        formData.append('description', story.description);
        formData.append('photo', story.photo);
        if (story.lat !== undefined && story.lat !== null) formData.append('lat', story.lat);
        if (story.lon !== undefined && story.lon !== null) formData.append('lon', story.lon);

        const response = await fetch('https://story-api.dicoding.dev/v1/stories', {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${story.token}`,
          },
          body: formData,
        });

        const result = await response.json();
        if (!result.error) {
          await db.delete('pending-stories', story.id);
          console.log('Story synced successfully:', story.id);
        }
      } catch (error) {
        console.error('Failed to sync individual story:', error);
      }
    }
  } catch (error) {
    console.error('Sync stories process failed:', error);
  }
}

self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-stories') {
    event.waitUntil(syncStories());
  }
});

// Push Notification Handling
self.addEventListener('push', (event) => {
  console.log('Push message received:', event);

  let data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch (e) {
    console.error('Push data is not valid JSON, using fallback data.');
    data = { title: 'Pembaruan StoryApp', body: event.data ? event.data.text() : 'Ada cerita baru untukmu!' };
  }

  const title = data.title || 'Cerita Baru di StoryApp!';
  const options = {
    body: data.body || 'Seseorang baru saja membagikan ceritanya. Lihat sekarang!',
    icon: '/favicon.svg',
    badge: '/favicon.svg',
    vibrate: [100, 50, 100],
    data: {
      url: data.url || '/',
    },
    actions: [
      {
        action: 'view-story',
        title: 'Lihat Detail',
        icon: '/favicon.svg'
      }
    ]
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// Notification Click Handling
self.addEventListener('notificationclick', (event) => {
  const notification = event.notification;
  const url = notification.data.url;

  notification.close();

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Find a window that is already open to that URL
      for (const client of clientList) {
        if (client.url === url && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window is open, open a new one
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    })
  );
});
